### ISSUE TITLE
About the performance of the model

### ISSUE THREAD

**Issue by zhanzl711** [lcwy220/Social-Recommendation#2]
According to your code, I did reproduce its result. But I reproduce NeuMF(one of author's baseline) at the same time, it get a better result than GraphRec. How can we explain this phenomenon？

**Comment by giorgos202** [comment]
Does NeuMF alleviate social information between the users?

**Comment by zhanzl711** [comment]
NeuMF does not use any social information
you can check my implementation from git@github.com:zhanzl711/SocialRecommendation.git

**Comment by lcwy220** [comment]
As far as I know, the TrustSVD also performs better than GraphRec. So we may need more research on how to use GNN to improve the SR problem.

**Comment by lcwy220** [comment]
Besides, you can try WU's DANSER(https://github.com/qitianwu/DANSER-WWW-19), it performs much better than most methods, and now I use it as the baseline. The only problem maybe is that it can not generalize to new items or users.
